### ISSUE TITLE
Version 3.0.0 not working with Angular version 5.1.3

### ISSUE THREAD

**Issue by salmankazmi** [cipchk/ngx-countdown#24]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-countdown/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

Throws this error when using version 3.0.0 with Angular 5.1.3. Gets fixed when I downgrade the countdown version to 2.1.0. I am not able to use the Countdowncomponent as a result.

## Expected behavior

The dependency should work fine and not pose errors with Angular versions.

## Environment

<pre><code>
Angular version: 5.1.3

ngx-countdown version: 3.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
Pls using `^2.0.0` version in angular5.

**Comment by salmankazmi** [comment]
As suggested will be using  v2. Lets see.
